### ISSUE TITLE
Implement different observing modes (e.g. Mosaicing)

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#84] opened 2022-05-06 08:25 UTC
Mosaicing -> Interferometer Mode
Driftscan -> Interferometer Mode or Auto Correlated
Multiple pointing -> Auto Correlated

We should have all three modes.
Implement Mosaic mode first, based on discussion  between ETH Team and Rohit. All telescope look at the same spot in one time step, then look at a different one at a different time step.

Combining seperate visibilites? --> Append, or Average, Interpolation?

_Originally posted by @cvoegele in https://github.com/i4Ds/Karabo-Pipeline/issues/74#issuecomment-1119374933_

**Comment by rohitcbscient** [comment] 2022-06-02 16:07
A simple working example script is added. But, this needs to refine.

**Comment by deiruch** [comment] 2023-01-27 09:20
Duplicate of #255

**Closed by deiruch** 2023-01-27 09:20 UTC
Labels: enhancement, prio-med
