### ISSUE TITLE
Imager overwrites cellsize 

### ISSUE THREAD

**Issue by jejestern** [i4Ds/Karabo-Pipeline#261] opened 2023-01-09 14:56 UTC
I currently get the following plot when the Imager is run:

![Bildschirmfoto vom 2023-01-09 15-49-08](https://user-images.githubusercontent.com/43879522/211336924-d77846ab-5c26-4106-af5e-aacede562d54.png)

This is how I call the Imager:
```
imager = Imager(visibility,imaging_npixel=4096,imaging_cellsize=50)
dirty = imager.get_dirty_image()
```

It seems to me as if the cellsize is getting overwritten since the dirty image only has a size of approximately 30" instead of several degrees.

**Comment by deiruch** [comment] 2023-01-13 13:15
@kenfus @Lukas113 can one of you tackle this with high priority?

Please also add a unit test to detect such a problem.

**Comment by kenfus** [comment] 2023-01-13 13:46
The imaging_cellsize-parameter is definitely affecting the plot and the code also passes it correctly to rascil. Maybe the units are off? Here is the test `test_dirty_image` with imaging_cellsize = 1:

![image](https://user-images.githubusercontent.com/47979198/212334423-ff226309-e446-487c-8595-d581a617aaf0.png)

And here with 3.878509448876288e-05:

![image](https://user-images.githubusercontent.com/47979198/212334548-8ba2afa5-a4c1-4d88-8268-258fa9781ead.png)

The parameter is definitely changing something.

**Comment by deiruch** [comment] 2023-01-13 13:57
Hm... @jejestern can you post a full code snippet to reproduce the problem?

**Comment by jejestern** [comment] 2023-01-13 15:12
for i in range(channel_num):
    chan_name = "result/Karabo_Catalog_Reconstruction/test_halo_sources_channel"+str(i)+"_"

    # We first define the telescope that we are going to use, which is MeerKAT
    telescope = Telescope.get_MEERKAT_Telescope()

    # Simulation of the interferometer
    simulation = InterferometerSimulation(vis_path=chan_name+".vis", channel_bandwidth_hz=10000000, time_average_sec=8, ignore_w_components=True, noise_enable=False, noise_seed="time", noise_freq="Range", noise_rms="Range", noise_start_freq=1.e9, noise_inc_freq=1.e8, noise_number_freq=24, noise_rms_start=5000, noise_rms_end=10000)

    # Observation settings
    observation = Observation(phase_centre_ra_deg=ra_deg, phase_centre_dec_deg=dec_deg, start_date_and_time=datetime(2000, 3, 20, 12, 6, 39), length=timedelta(hours=0, minutes=5, seconds=0, milliseconds=0), number_of_time_steps=10, start_frequency_hz=c.value/(0.21*(1+redshift_channel[i])), frequency_increment_hz=freq_bin, number_of_channels=channel_num)

    # In this step we mask the dataframe to the respective frequency bin. Since we're using 21cm sources there's a one to one correspondence between redshift and distance.
    sky_bin = copy.deepcopy(sky_filter)
    sky_bin_idx = np.where((z_obs_filter>redshift_channel[i])&(z_obs_filter<redshift_channel[i+1]))
    sky_bin.sources = sky_bin.sources[sky_bin_idx]
    print(sky_bin.to_array().shape,sky_bin[:,2],ra_deg,dec_deg)

    visibility = simulation.run_simulation(telescope, sky_bin, observation)

    imager = Imager(visibility, imaging_npixel=2048 * 2,imaging_cellsize=4.3e-5,imaging_dopsf=True)
    dirty = imager.get_dirty_image()
    dirty.write_to_file("test" + str(i) + ".fits")
    dirty.plot(title='Flux Density [Jy]')

This is the code I use, which produces the problem. If I replace the imager in the code by the imager from oskar instead of the one from karabo, I do not have this problem.
Below the corresponding WCS information:
![Bildschirmfoto vom 2023-01-13 16-04-17](https://user-images.githubusercontent.com/43879522/212352137-3e8c4d87-4f95-45af-9107-35fbc00772d4.png)
When I use the test scripts it works for me as well. 
@kenfus what do you mean by: maybe the units are off? Also @kenfus something in your test seems not to work, since the position of the source changes when you are changing the cellsize..?

**Comment by kenfus** [comment] 2023-01-16 09:01
Yep, I mean that the labels are wrong. I am currently looking into it.

**Comment by kenfus** [comment] 2023-01-17 11:27
It took me a while to make rascil 1.0.0, but it seems that it does not have this problem because the labels adapt when the cellsize is changed.

![image](https://user-images.githubusercontent.com/47979198/212885906-0a684402-9997-4c96-bbc7-a18950db92e6.png)

![image](https://user-images.githubusercontent.com/47979198/212885969-948e00bc-fdee-4c8e-9885-2515ad1e74db.png)

So I guess this will be fixed when we update Rascil to 1.0.0 and also use their plotting functions #233

**Comment by jejestern** [comment] 2023-01-18 12:13
This might mean, that the problem I have currently with the cellsize might also be fixed, when Rascil is updated.

**Comment by kenfus** [comment] 2023-01-19 15:13
I think we need to rewrite a bit of Karabo to use the functionality of Rascil. Rascil 0.7.0 has already things like `show_image`.

**Comment by kenfus** [comment] 2023-01-20 15:30
@rohitcbscient and I found out that the imager is actually correct:

![image](https://user-images.githubusercontent.com/47979198/213736186-d6efdca5-a6bc-4b4f-ab38-7300a1e3b94b.png)
![image](https://user-images.githubusercontent.com/47979198/213736287-77ec941e-a5d7-4ef3-9d9c-a68acee5a56e.png)

@jejestern is correct, the cellsize is automatically overwritten. Now you can pass a parameter to disable it.

**Closed** 2023-01-27 08:49 UTC
Labels: question, prio-high, user-request
