### ISSUE TITLE
Docker installations should be tested

### ISSUE THREAD

**Issue by kenfus** [i4Ds/Karabo-Pipeline#264] opened 2023-01-12 13:42 UTC
Best to test them after each new release (could lead to stress at the end of the month).

**Comment by deiruch** [comment] 2023-01-13 13:16
Would probably sense to run the tests together with other monthly tests on CSCS, no? (see #170)

**Comment by deiruch** [comment] 2023-01-13 15:14
Duplicate of #189

**Closed by deiruch** 2023-01-13 15:14 UTC
Labels: enhancement, prio-med, testing
