### ISSUE TITLE
Karabo storage diet

### ISSUE THREAD

**Issue by fschramka** [i4Ds/Karabo-Pipeline#270] opened 2023-01-16 14:40 UTC
Karabo gets bigger and bigger due to more functionallity. 

Here is the top 10:

01. nsight-compute-2022.2.0.13-0.json:                      "size":  485381969,
02. libcublas-dev-11.10.1.25-h0c8ac2b_0.json:            "size":  324267418,
03. libcusparse-dev-11.7.3.50-hc644b96_0.json:         "size":  315781272,
04. libcublas-11.10.1.25-he442b6f_0.json:                   "size":  314450443,
05. libcufft-dev-10.7.2.50-h59a5ac8_0.json:                "size":  205997732,
06. libcusparse-11.7.3.50-h6aaafad_0.json:                  "size":  155592022,
07. libnpp-11.7.3.21-h3effbd9_0.json:                         "size":  124218053,
08. libnpp-dev-11.7.3.21-hb6476a9_0.json:                "size":  121327534,
09. cuda-nvvp-11.7.50-hd2289d5_0.json:                   "size":  119873153,
10. cuda-nsight-11.7.50-0.json:                                 "size":  119141042,

I checked the karabo_dev_env with the following command:
`grep '"size":' ${CONDA_PREFIX}/conda-meta/*.json | sort -k3rn | sed 's/.*conda-meta\///g' | column -t`

Nvidia nsight for example is a GPU profiler - we have it twice in the top 10, place 1 & 10 with around 600MB in total.

Do we need to ship such big packages with Karabo if we do not use those tools?

**Comment by deiruch** [comment] 2023-01-16 14:41
Duplicate of #235

**Closed by deiruch** 2023-01-16 14:41 UTC
Labels: enhancement, question
