### ISSUE TITLE
Conda: Building environment shouldn't take ~40 minutes 

### ISSUE THREAD

**Issue by deiruch** [i4Ds/Karabo-Pipeline#213] opened 2022-12-02 09:34 UTC
Jennifer's installation took approx. 40 minutes. Most of the time was spent resolving all dependencies. This could get better with newer RASCIL or PyBSDF versions. Or we could document Mamba use.

**Comment by kenfus** [comment] 2022-12-02 10:53
Installing Karabo as user via miniconda takes for me also currently around 25 minutes. With mamba, it is down to around ~2 min. Of those, 1 minute is downloading and extracting stuff. 

I also reinstalled miniconda to see if it would get quicker. It did not.

**Comment by Lukas113** [comment] 2022-12-07 12:48
Can't reproduce. Installing it on Ubunut22.04 takes about 1 1/2 min in a fresh environment.

**Comment by Lukas113** [comment] 2022-12-07 15:28
I just did the installation of Karabo 0.11.0, python=3.9 on piz-daint. It took about 3 minutes. We are working on newer RASCIL and PyBDSF builds, but I can't really think of a reason why I took so long besides of a different python or karabo version assuming a fresh virtual environment.

**Comment by deiruch** [comment] 2023-01-13 13:45
Was this ever solved? Is this still a problem? (Maybe @jejestern can provide more details?)

@Lukas113 @kenfus  Should we just update our documentation to mamba instead of conda?

**Comment by kenfus** [comment] 2023-01-18 10:42
We should @deiruch, especially now with https://www.anaconda.com/blog/conda-is-fast-now Maybe as a small hint?

**Comment by jejestern** [comment] 2023-01-20 21:31
It is still a problem if you use anaconda. I now did a complete refresh: Installing miniconda and adding the new conda-libmamba-solver as solver (https://www.anaconda.com/blog/conda-is-fast-now), like @kenfus suggested. 
Installing karabo with  miniconda using the libmamba solver takes between 1-2 min and therefore solves the problem. 
However, I was not able to install the libmamba solver on anaconda. Also, when I installed karabo the first time, it failed, because I needed to change some of the environment variables.

**Comment by Lukas113** [comment] 2023-01-23 09:19
I can confirm that the solving with miniconda & libmamba is very fast. For me, the installation of the user and dev-env took about 20 min, while the environment solving took less than 1 minute. I also remember having problems installing libmamba on anaconda. Based on this, I will adjust the installation instructions accordingly with the recommendation to use miniconda & libmamba with the hint that installing without the libmamba solver might take a bit longer.

**Comment by elastufka** [comment] 2023-11-28 10:08
any tips on installation with a HPC server where I cannot write to the environment? I tried with the instructions on readthedocs and it never solved the environment...

trying to change the solver I get this error:

EnvironmentNotWriteableError: The current user does not have write permissions to the target environment. 
   environment location: /opt/ebsofts/Anaconda3/2022.05

also I cannot install mamba.

**Comment by Lukas113** [comment] 2023-11-28 11:11
@elastufka we are aware that installation can be difficult without the libmamba solver and currently we don't have any good solution other than use the solver. 

Your issue is, that you're using a root-installation of conda where the libmamba-solver is not available (because it lives in the base environment where you don't have permissions). There are two possible solutions I can provide:

Either, ask the admin to install the libmamba-solver to the root-conda and try the installation again in your virtual-env.

OR I recommend install miniconda in your home. The overhead is not that much since the root-installation of conda installs the virtual environment of a user in their home anyway. I've just tested the following steps on CSCS where I didn't encounter any issues (the whole process took about 5 min):

```
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source .bashrc
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
conda create -y -n karabo
conda activate karabo
conda install -y -c nvidia/label/cuda-11.7.0 -c i4ds -c conda-forge karabo-pipeline
```

If you have any issues or are not able to use a libmamba-solver, I'll have a look into it. But that may take a while because currently I'm not sure how to do the installation without a libmamba-solver without any issues.

**Comment by elastufka** [comment] 2023-11-28 12:56
> 
> ```
> wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
> bash Miniconda3-latest-Linux-x86_64.sh
> source .bashrc
> conda install -n base conda-libmamba-solver
> conda config --set solver libmamba
> conda create -y -n karabo
> conda activate karabo
> conda install -y -c nvidia/label/cuda-11.7.0 -c i4ds -c conda-forge karabo-pipeline
> ```
> 

This worked, thanks @Lukas113 ! I don't know how long it took (long enough for me to look away and forget about it) but I would say half an hour max.

**Comment by Lukas113** [comment] 2023-11-28 13:22
Great!

Hmm, not sure why there's such a large difference in time for dependency-resolving and installation. I think I didn't use any cached packages since I removed miniconda on the cluster entirely to reproduce the steps mentioned above.

If there's anything else where you need support, don't hesitate to open or reopen an issue.

**Closed** 2023-11-28 13:22 UTC
Labels: enhancement, prio-high
