### ISSUE TITLE
Test Noise Implementation of OSKAR

### ISSUE THREAD

**Issue by cvoegele** [i4Ds/Karabo-Pipeline#40] opened 2022-02-25 09:12 UTC
- [ ] benchmark
- [ ] add interface if the benchmark is successful

**Comment by deiruch** [comment] 2022-02-25 09:49
Duplicate of #23

**Comment by cvoegele** [comment] 2022-07-01 08:13
https://ska-telescope.gitlab.io/sim/oskar/settings/settings-interferometer.html?highlight=noise#interferometer-noise-seed

**Comment by deiruch** [comment] 2022-08-19 08:17
@rohitcbscient Tested this on oskar & already wrote unit tests. Noise is solely uniform RMS noise.

**Comment by rohitcbscient** [comment] 2022-09-02 05:43
I have created a pull request for the same. The system noise is implemented in accordance with Oskar.

**Closed by rohitcbscient** 2022-09-02 05:43 UTC
Labels: enhancement
